name: CI

on: [push]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test'
    runs-on: [ubuntu-latest]
    env:
      LANG: en_US.UTF-8

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.11.0
          dest: test-job
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Run Tests
        run: pnpm run exam
        env:
          TZ: Europe/Vienna
